POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5ydSIsImV4cCI6MTcyMjYyMDI1NSwidXNlcklkIjoyfQ.wZI5Mv_Cv2f7ac1_el-QqBy-n88Z9Fd-KahaKE6RY8c

{
    "name": "Test event 12312",
    "description": "Tesxasd asd",
    "location": "It's doesn't matter",
    "dateTime": "2025-01-01T15:30:00.000Z"
}