POST http://localhost:8080/events
content-type: application/json

{
    "name": "For delete",
    "description": "Will deleted",
    "location": "It's doesn't matter",
    "dateTime": "2025-01-01T15:30:00.000Z"
}